#!/usr/bin/env python3
"""
Build a Python training corpus from the local filesystem.

Scans the stdlib and site-packages, filters out the material that would teach
the model bad habits (generated code, vendored trees, minified blobs, test
fixtures), deduplicates, fits a byte-level BPE, and writes uint16 token streams
to train.bin / val.bin.

    python3 prepare_data.py --out data --vocab 8192

The split is by file, not by chunk, so no function appears in both halves.
"""

import os
import re
import sys
import json
import time
import site
import random
import hashlib
import argparse
import sysconfig

import numpy as np

EOT = "<|endoftext|>"
SELF_OPEN = "<self>"
SELF_CLOSE = "</self>"
SPECIALS = [EOT, SELF_OPEN, SELF_CLOSE]

# Directory names that hold code we do not want to imitate.
SKIP_DIRS = {
    "__pycache__", ".git", "node_modules", "vendor", "_vendor", "third_party",
    "site-packages/boto3", "test", "tests", "testing", "idlelib", "lib2to3",
    "fixtures", "migrations", ".mypy_cache", ".pytest_cache", "benchmarks",
}
# Path fragments that reliably mark generated or vendored files.
SKIP_PATTERNS = re.compile(
    r"(_pb2|_pb2_grpc|\.generated\.|/vendored?/|/_vendor/|/third_party/"
    r"|/data/[a-z0-9-]+/\d{4}-\d{2}-\d{2}/|conftest\.py$|setup\.py$)"
)

MAX_BYTES = 192 * 1024      # bigger than this is almost always generated
MIN_BYTES = 200             # stubs teach nothing
MAX_LINE = 400              # a long line means minified or a data blob


def is_reasonable(path, text):
    """Cheap quality gate. Returns None if fine, else the reason to skip."""
    n = len(text)
    if n < MIN_BYTES:
        return "tiny"
    if n > MAX_BYTES:
        return "huge"
    lines = text.split("\n")
    if max((len(l) for l in lines), default=0) > MAX_LINE:
        return "long-line"
    # generated files usually say so in the first few lines
    head = "\n".join(lines[:5]).lower()
    if "do not edit" in head or "auto-generated" in head or "autogenerated" in head:
        return "generated"
    # a file that is mostly data literals is not a code lesson
    code_ish = sum(1 for l in lines if l.lstrip().startswith(
        ("def ", "class ", "if ", "for ", "while ", "return ", "import ",
         "from ", "with ", "try:", "elif ", "else:", "@")))
    if code_ish < max(3, len(lines) * 0.02):
        return "data-heavy"
    return None


def collect_roots(extra):
    roots = {sysconfig.get_paths()["stdlib"]}
    for p in site.getsitepackages() + [site.getusersitepackages()]:
        if os.path.isdir(p):
            roots.add(p)
    for p in extra:
        if os.path.isdir(p):
            roots.add(os.path.abspath(p))
    return sorted(roots)


def scan(roots, verbose=True):
    """Yield (path, text) for every file that passes the quality gate."""
    seen_hashes = set()
    stats = {"seen": 0, "kept": 0, "dupe": 0}
    reasons = {}
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS
                           and not d.startswith(".")]
            for name in filenames:
                if not name.endswith(".py"):
                    continue
                path = os.path.join(dirpath, name)
                if SKIP_PATTERNS.search(path):
                    reasons["pattern"] = reasons.get("pattern", 0) + 1
                    continue
                stats["seen"] += 1
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        text = f.read()
                except (OSError, UnicodeDecodeError):
                    reasons["unreadable"] = reasons.get("unreadable", 0) + 1
                    continue
                why = is_reasonable(path, text)
                if why:
                    reasons[why] = reasons.get(why, 0) + 1
                    continue
                digest = hashlib.blake2b(text.encode("utf-8"),
                                         digest_size=16).digest()
                if digest in seen_hashes:
                    stats["dupe"] += 1
                    continue
                seen_hashes.add(digest)
                stats["kept"] += 1
                yield path, text
    if verbose:
        print(f"  scanned {stats['seen']:,} | kept {stats['kept']:,} | "
              f"exact dupes {stats['dupe']:,}", file=sys.stderr)
        for why, n in sorted(reasons.items(), key=lambda kv: -kv[1]):
            print(f"    skipped {n:>7,}  {why}", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data_char")
    ap.add_argument("--val-frac", type=float, default=0.005)
    ap.add_argument("--extra-root", action="append", default=[])
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    roots = collect_roots(args.extra_root)
    print("roots:")
    for r in roots:
        print(f"  {r}")

    # ---- pass 1: collect file list and text to a single flat corpus file ----
    print("\npass 1: scanning and filtering ...")
    t0 = time.time()
    flat = os.path.join(args.out, "corpus.txt")
    paths = []
    total_bytes = 0
    with open(flat, "w", encoding="utf-8") as out:
        for path, text in scan(roots):
            if not text.endswith("\n"):
                text += "\n"
            out.write(text)
            out.write(EOT + "\n")
            paths.append((path, len(text)))
            total_bytes += len(text)
    print(f"  {len(paths):,} files, {total_bytes/1e6:.1f} MB "
          f"in {time.time()-t0:.1f}s -> {flat}")
    if not paths:
        print("no files survived filtering", file=sys.stderr)
        return 1

    from minagi.tokenizer import ByteTokenizer
    tok = ByteTokenizer()
    print("\nbyte level: vocab 265, no tokenizer to fit")
    return _encode(args, flat, tok, paths, total_bytes, roots)


def _encode(args, flat, tok, paths, total_bytes, roots):
    # ---- pass 2: encode, splitting by file ----
    print("\npass 2: encoding ...")
    rng = random.Random(args.seed)
    eot_id = tok.token_to_id(EOT)
    if eot_id is None:          # byte level has no multi-char special token
        eot_id = 0

    train_path = os.path.join(args.out, "train.bin")
    val_path = os.path.join(args.out, "val.bin")
    counts = {"train": 0, "val": 0}
    t0 = time.time()

    with open(train_path, "wb") as ftr, open(val_path, "wb") as fva, \
            open(flat, "r", encoding="utf-8") as src:
        buf, batch, which = [], [], []
        doc = []

        def flush():
            if not batch:
                return
            for enc, split in zip(tok.encode_batch(batch), which):
                ids = np.array(enc.ids + [eot_id], dtype=np.uint16)
                (ftr if split == "train" else fva).write(ids.tobytes())
                counts[split] += len(ids)
            batch.clear()
            which.clear()

        for line in src:
            if line.rstrip("\n") == EOT:
                text = "".join(doc)
                doc.clear()
                if text.strip():
                    batch.append(text)
                    which.append("val" if rng.random() < args.val_frac
                                 else "train")
                if len(batch) >= 512:
                    flush()
                    done = counts["train"] + counts["val"]
                    print(f"\r  {done/1e6:>7.1f}M tokens "
                          f"({time.time()-t0:.0f}s)", end="", file=sys.stderr)
            else:
                doc.append(line)
        text = "".join(doc)
        if text.strip():
            batch.append(text)
            which.append("train")
        flush()

    print()
    total = counts["train"] + counts["val"]
    ratio = total_bytes / max(total, 1)
    meta = {
        "vocab_size": tok.get_vocab_size(),
        "train_tokens": counts["train"],
        "val_tokens": counts["val"],
        "files": len(paths),
        "bytes": total_bytes,
        "chars_per_token": round(ratio, 3),
        "tokenizer": "byte",
        "eot_id": eot_id,
        "self_open_id": tok.token_to_id(SELF_OPEN),
        "self_close_id": tok.token_to_id(SELF_CLOSE),
        "roots": roots,
    }
    with open(os.path.join(args.out, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    print(f"\ntrain {counts['train']:,} tokens ({counts['train']*2/1e6:.0f} MB)")
    print(f"val   {counts['val']:,} tokens")
    print(f"compression {ratio:.2f} chars/token")
    print(f"wrote {train_path}, {val_path}, meta.json")
    os.remove(flat)
    return 0


if __name__ == "__main__":
    sys.exit(main())
